
/*SIMPLE ASSEMBLER FOR 8085
  Written By Madhur
*/

#include "types.h"

char filename[255];
int symindex=0;
char oper1[100][100],oper2[100][100],lbl[100][100];
char opc[100][100];
int motcount;
char machine[100][10];
char *regs[]={"A","B","C","D","E","H","L","M","8","SP","PSW"};

struct mot mottable[500];
struct ST sym[100];

int input();
int disp();
int pass1();
int pass2();
int writeoutfile();
int main(int argc,char **argv)
{

	char ofile[255];
	int j,res;

	if(argc==1)
	{
		printf("\nUse:asm85 [option] <filename>");
		printf("\noptions:");
		printf("\n-o <file> - Give the output filename");
		printf("\n-s  Show the machine opcode table");
		printf("\n-i  Enter opcodes into opcode table");
		printf("\nDefault mot file is mot.dat");
		printf("\n");
		return EXIT_SUCCESS;
	}

	if(argc>=2)
	{
		int flag=1;
		j=strcmp(*(argv+1),"-o");
		if(j==0)
		{
			flag=0;
			if(*(argv+2)==NULL)
			{
				printf("\nYou must specify an output file");
				return EXIT_SUCCESS;
			}
			else
				strcpy(ofile,*(argv+2));
			if(*(argv+3)==NULL)
			{
				printf("\nasm85: no input files specified");
				return EXIT_SUCCESS;
			}
			strcpy(filename,*(argv+3));
		}
		j=strcmp(*(argv+1),"-s");
		if(j==0)
		{
			char *file[]={"sdf","mot.dat"};
			flag=0;
			disp(2,&file);
			exit(EXIT_SUCCESS);
		}
		j=strcmp(*(argv+1),"-i");
		if(j==0)
		{
			char *file[]={"df","mot.dat"};
			flag=0;
			input(2,&file);
			exit(EXIT_SUCCESS);
		}

		if(flag)
		{
			strcpy(filename,*(argv+1));
			strcpy(ofile,"c:\\outfile.txt");
		}
	}

	else
	{
		strcpy(filename,*(argv+1));
		strcpy(ofile,"c:\\outfile.txt");
	}


	pass1();

	pass2();

	/*ASSEMBLING DONE, WRITE THE OUPUT FILES */
	res=writeoutfile(ofile);
	if(res==1)
	{
		fprintf(stderr,"\nAn error occur while writing to output file");
		return EXIT_FAILURE;
	}
	else
		printf("\nOutput written to %s",ofile);


	return EXIT_SUCCESS;
}

int writeoutfile(const char* ofile)
{
	int i,j;
	int mindex=0,res,lc=0;
	FILE *OUTFILE=fopen(ofile,"w");
	if(OUTFILE==NULL)
	{
		printf("\nCannot open file for output");
		return 1;
	}

	fprintf(OUTFILE,"\t\tAssembly output for %s\n\n",filename);
	fprintf(OUTFILE,"\t\tGenerated by asm85\n");

	fprintf(OUTFILE,"LC\tLabel\tInstruction\t\tMachine bytes\n");
	for(i=0;i<lines;++i)		//repair here
	{

		int index,inslen;
		res=strcmp(opc[i],"");
		if(res==0)
			continue;	//skip the last newline
		res=strcmp(lbl[i],"");
		fprintf(OUTFILE,"%x\t",lc);	//print lc in hex
		if(res!=0)
			fprintf(OUTFILE,"%s:\t",lbl[i]);	//print the label if it is present
		else
			fprintf(OUTFILE,"\t");

		fprintf(OUTFILE,"%s\t%s %s\t\t",opc[i],oper1[i],oper2[i]);

		index=getmotindex(opc[i],oper1[i],oper2[i]);
		inslen=mottable[index].length;
		lc=lc+inslen;
		for(j=0;j<inslen;++j)
		{
			fprintf(OUTFILE,"%s ",machine[mindex]);
			mindex++;
		}
		fprintf(OUTFILE,"\n");
	}

	//print the symbol table
	fprintf(OUTFILE,"\n\n\t\tSymbol Table\n");
	fprintf(OUTFILE,"\t\t============\n\n");
	fprintf(OUTFILE,"Symbol\t\tValue\t\tLength\n");
	for(i=0;i<=symindex;++i)
	{
		res=strcmp(sym[i].name,"");
		if(res==0)
			continue;	//ignore the no symbol case
		fprintf(OUTFILE,"%s\t\t%x\t\t%x\n",sym[i].name,sym[i].value,sym[i].length);
	}

	fclose(OUTFILE);
	return 0;
}




