//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Script1.rc
//
#define IDD_PROCESS                     101
#define IDC_ADD                         1002
#define IDC_REMOVE                      1003
#define IDC_EXIT                        1004
#define IDC_LIST1                       1005
#define IDC_LIST2                       1006
#define IDC_REFRESH                     1007
#define IDI_EXIT                        5000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
