//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by button.rc
//
#define IDD_DIALOG1                     101
#define IDI_ICON1                       102
#define IDC_LIST1                       1000
#define IDSTART                         1001
#define IDQUIT                          1002
#define IDEDIT                          1004
#define IDREMOVE                        1005
#define IDC_ICON1                       -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
