//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Script1.rc
//
#define IDD_DIALOG1                     101
#define IDD_DIALOG2                     102
#define IDC_EDHWND                      1000
#define IDC_BUTHWND                     1001
#define IDEXIT                          1002
#define IDC_NAGHWND                     1003
#define IDC_HWND                        1004
#define IDC_BRUTE                       1005
#define IDC_CURRENT                     1006
#define IDC_WINDOW                      1007
#define IDCLASS                         1008
#define IDC_ID                          1009
#define IDC_BUTID                       1010
#define IDC_BUTNAGID                    1011
#define IDABOUT                         1012
#define IDC_TESTSET                     1013
#define IDC_TESTPRESS                   1014
#define IDC_TESTPRESS1                  1015
#define IDTEST                          1016
#define IDC_SUSPEND                     1017
#define IDC_COUNT                       1018
#define IDC_RESET                       1019

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1021
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
